# Generated by Django 2.0.5 on 2018-07-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_stock_share_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='share_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
