# Generated by Django 2.0.5 on 2018-07-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20180721_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='share_price',
        ),
        migrations.AlterField(
            model_name='investment',
            name='acquired_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='investment',
            name='recent_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='share_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shares',
            field=models.FloatField(),
        ),
    ]
